### Getting wind and precipidation data from NOAA

The following notebook was used to get csv files with daily readings of wind and rain data from NOAA. The following link can be used to get historical weather data from NOAA: https://www.ncdc.noaa.gov/cdo-web/search

In [1]:
import pandas as pd
import numpy as np

In [2]:
def load_weather(df):
    
    df = df.loc[:, ["STATION", "NAME", "LATITUDE", "LONGITUDE", "DATE", "PRCP", "WSF2", "WSF5"]]
    
    df["DATE"] = pd.to_datetime(df["DATE"])
    
    df.set_index("DATE", inplace=True)
    
    return df

### Atlantic City, New Jersey

In [4]:
acnj = pd.read_csv("./noaa-precip-wind-csv-raw-data/atlantic-city-nj.csv")

acnj = load_weather(acnj)

acnj.to_csv("./noaa-precip-wind-tables/atlantic-city-nj.csv")

acnj.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.00,6.9,19.0
2010-01-02,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.00,14.1,34.9
2010-01-03,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.01,28.0,45.0
2010-01-04,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.00,10.1,25.1
2010-01-05,USW00013724,"ATLANTIC CITY MARINA, NJ US",39.37778,-74.42361,0.00,8.9,23.0

### Westerly State Airport, Washington County, Rhode Island

In [5]:
wcri = pd.read_csv("./noaa-precip-wind-csv-raw-data/washington-county-ri.csv")

wcri = load_weather(wcri)

wcri.to_csv("./noaa-precip-wind-tables/washington-county-ri.csv")

wcri.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.04,8.9,10.1
2010-01-02,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.15,21.0,33.1
2010-01-03,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.00,23.0,36.9
2010-01-04,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.00,18.1,30.0
2010-01-05,USW00014794,"WESTERLY STATE AIRPORT, RI US",41.34972,-71.79889,0.00,10.1,18.1

### New Bedford, MA

In [6]:
nbma = pd.read_csv("./noaa-precip-wind-csv-raw-data/new-bedford-ma.csv")

nbma = load_weather(nbma)

nbma.to_csv("./noaa-precip-wind-tables/new-bedford-ma.csv")

nbma.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.02,8.1,10.1
2010-01-02,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.10,25.1,36.0
2010-01-03,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.00,29.1,38.0
2010-01-04,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.00,18.1,23.9
2010-01-05,USW00094726,"NEW BEDFORD MUNICIPAL AIRPORT, MA US",41.67639,-70.95833,0.00,12.1,16.1

### Boston, MA

In [7]:
boma = pd.read_csv("./noaa-precip-wind-csv-raw-data/boston-ma.csv")

boma = load_weather(boma)

boma.to_csv("./noaa-precip-wind-tables/boston-ma.csv")

boma.head()

                STATION           NAME  LATITUDE  LONGITUDE  PRCP  WSF2  WSF5
DATE
2010-01-01  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.00  15.0  19.9
2010-01-02  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.43  30.0  38.0
2010-01-03  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.20  31.1  40.9
2010-01-04  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.00  23.0  31.1
2010-01-05  USW00014739  BOSTON, MA US   42.3606   -71.0097  0.00  17.0  23.9

### Bridgeport, CT

In [8]:
brct = pd.read_csv("./noaa-precip-wind-csv-raw-data/bridgeport-ct.csv")

brct = load_weather(brct)

brct.to_csv("./noaa-precip-wind-tables/bridgeport-ct.csv")

brct.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.03,8.1,12.1
2010-01-02,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.06,25.9,34.9
2010-01-03,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.07,28.0,36.0
2010-01-04,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.00,19.9,23.9
2010-01-05,USW00094702,"IGOR I SIKORSKY MEMORI AIRPORT, CT US",41.1583,-73.1289,0.00,21.0,30.0

### New Haven, CT

In [9]:
nhct = pd.read_csv("./noaa-precip-wind-csv-raw-data/new-haven-ct.csv")

nhct = load_weather(nhct)

nhct.to_csv("./noaa-precip-wind-tables/new-haven-ct.csv")

nhct.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.02,8.1,10.1
2010-01-02,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.00,21.9,38.0
2010-01-03,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.00,25.1,38.0
2010-01-04,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.00,17.0,28.0
2010-01-05,USW00014758,"NEW HAVEN TWEED AIRPORT, CT US",41.26389,-72.88722,0.00,16.1,23.9

### New London, CT

In [10]:
nlct = pd.read_csv("./noaa-precip-wind-csv-raw-data/new-london-ct.csv")

nlct = load_weather(nlct)

nlct.to_csv("./noaa-precip-wind-csv-raw-data/new-london-ct.csv")

nlct.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,8.1,10.1
2010-01-02,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,31.1,40.9
2010-01-03,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,31.1,42.9
2010-01-04,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,21.0,28.0
2010-01-05,USW00014707,"GROTON NEW LONDON AIRPORT, CT US",41.3275,-72.04944,0.0,17.0,21.0

### Newport, RI

In [11]:
npri = pd.read_csv("./noaa-precip-wind-csv-raw-data/newport-ri.csv")

npri = load_weather(npri)

npri.to_csv("./noaa-precip-wind-tables/newport-ri.csv")

npri.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,13.0,16.1
2010-01-02,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,25.1,36.9
2010-01-03,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,28.0,38.9
2010-01-04,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,21.0,30.0
2010-01-05,USW00014787,"NEWPORT STATE AIRPORT, RI US",41.53333,-71.28333,0.0,16.1,21.9

### Manhattan, New York City, NY

In [12]:
mnyc = pd.read_csv("./noaa-precip-wind-csv-raw-data/manhattan-ny.csv")

mnyc = load_weather(mnyc)

mnyc.to_csv("noaa-precip-wind-tables/manhattan-ny.csv")

mnyc.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00094728,"NY CITY CENTRAL PARK, NY US",40.77898,-73.96925,0.03,16.1,21.9
2010-01-02,USW00094728,"NY CITY CENTRAL PARK, NY US",40.77898,-73.96925,0.02,21.9,34.9
2010-01-03,USW00094728,"NY CITY CENTRAL PARK, NY US",40.77898,-73.96925,0.00,25.9,38.9
2010-01-04,USW00094728,"NY CITY CENTRAL PARK, NY US",40.77898,-73.96925,0.00,17.0,23.9
2010-01-05,USW00094728,"NY CITY CENTRAL PARK, NY US",40.77898,-73.96925,0.00,17.0,23.9

### Providence, RI

In [13]:
prri = pd.read_csv("./noaa-precip-wind-csv-raw-data/providence-ri.csv")

prri = load_weather(prri)

prri.to_csv("./noaa-precip-wind-tables/providence-ri.csv")

prri.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014765,"PROVIDENCE, RI US",41.7225,-71.4325,0.01,13.0,17.0
2010-01-02,USW00014765,"PROVIDENCE, RI US",41.7225,-71.4325,0.27,25.1,33.1
2010-01-03,USW00014765,"PROVIDENCE, RI US",41.7225,-71.4325,0.04,25.9,36.0
2010-01-04,USW00014765,"PROVIDENCE, RI US",41.7225,-71.4325,0.00,21.9,32.0
2010-01-05,USW00014765,"PROVIDENCE, RI US",41.7225,-71.4325,0.00,14.1,19.9

### Ocean City, MD

In [14]:
ocmd = pd.read_csv("./noaa-precip-wind-csv-raw-data/ocean-city-md.csv")

ocmd = load_weather(ocmd)

ocmd.to_csv("./noaa-precip-wind-tables/ocean-city-md.csv")

ocmd.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00093786,"OCEAN CITY MUNICIPAL AIRPORT, MD US",38.30833,-75.12389,0.02,21.0,79.0
2010-01-02,USW00093786,"OCEAN CITY MUNICIPAL AIRPORT, MD US",38.30833,-75.12389,0.00,28.0,40.9
2010-01-03,USW00093786,"OCEAN CITY MUNICIPAL AIRPORT, MD US",38.30833,-75.12389,0.00,28.0,38.9
2010-01-04,USW00093786,"OCEAN CITY MUNICIPAL AIRPORT, MD US",38.30833,-75.12389,0.00,19.9,31.1
2010-01-05,USW00093786,"OCEAN CITY MUNICIPAL AIRPORT, MD US",38.30833,-75.12389,0.00,21.0,25.9

### Baltimore, MD

In [5]:
blmd = pd.read_csv("./noaa-precip-wind-csv-raw-data/baltimore-md.csv")

blmd = load_weather(blmd)

blmd.to_csv("./noaa-precip-wind-tables/baltimore-md.csv")

blmd.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00093721,"BALTIMORE WASHINGTON INTERNATIONAL AIRPORT, MD US",39.1733,-76.684,0.03,23.0,30.0
2010-01-02,USW00093721,"BALTIMORE WASHINGTON INTERNATIONAL AIRPORT, MD US",39.1733,-76.684,0.00,33.1,47.0
2010-01-03,USW00093721,"BALTIMORE WASHINGTON INTERNATIONAL AIRPORT, MD US",39.1733,-76.684,0.00,34.9,47.0
2010-01-04,USW00093721,"BALTIMORE WASHINGTON INTERNATIONAL AIRPORT, MD US",39.1733,-76.684,0.00,21.9,31.1
2010-01-05,USW00093721,"BALTIMORE WASHINGTON INTERNATIONAL AIRPORT, MD US",39.1733,-76.684,0.00,21.9,30.0

### Portland, ME

In [16]:
pome = pd.read_csv("./noaa-precip-wind-csv-raw-data/portland-me.csv")

pome = load_weather(pome)

pome.to_csv("./noaa-precip-wind-tables/portland-me.csv")

pome.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00014764,"PORTLAND JETPORT, ME US",43.64222,-70.30444,0.08,15.0,19.9
2010-01-02,USW00014764,"PORTLAND JETPORT, ME US",43.64222,-70.30444,0.29,29.1,40.0
2010-01-03,USW00014764,"PORTLAND JETPORT, ME US",43.64222,-70.30444,0.12,30.0,45.0
2010-01-04,USW00014764,"PORTLAND JETPORT, ME US",43.64222,-70.30444,0.00,21.9,32.0
2010-01-05,USW00014764,"PORTLAND JETPORT, ME US",43.64222,-70.30444,0.00,17.0,23.9

### Martha's Vineyard, MA

In [17]:
mvma = pd.read_csv("./noaa-precip-wind-csv-raw-data/marthas-vineyard-ma.csv")

mvma = load_weather(mvma)

mvma.to_csv("./noaa-precip-wind-tables/marthas-vineyard-ma.csv")

mvma.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00094724,"VINEYARD HAVEN MARTHAS VINEYARD AIRPORT, MA US",41.39306,-70.615,0.06,14.1,16.1
2010-01-02,USW00094724,"VINEYARD HAVEN MARTHAS VINEYARD AIRPORT, MA US",41.39306,-70.615,0.08,29.1,40.9
2010-01-03,USW00094724,"VINEYARD HAVEN MARTHAS VINEYARD AIRPORT, MA US",41.39306,-70.615,0.00,28.0,42.9
2010-01-04,USW00094724,"VINEYARD HAVEN MARTHAS VINEYARD AIRPORT, MA US",41.39306,-70.615,0.00,21.9,30.0
2010-01-05,USW00094724,"VINEYARD HAVEN MARTHAS VINEYARD AIRPORT, MA US",41.39306,-70.615,0.00,8.9,14.1

### Virginia Beach, VA

In [6]:
vbva = pd.read_csv("./noaa-precip-wind-csv-raw-data/virginia-beach-va.csv")

vbva = load_weather(vbva)

vbva.to_csv("./noaa-precip-wind-tables/virginia-beach-va.csv")

vbva.head()

,STATION,NAME,LATITUDE,LONGITUDE,PRCP,WSF2,WSF5
DATE,,,,,,,
2010-01-01,USW00013769,"OCEANA NAS, VA US",36.81667,-76.03333,0.01,25.9,35.1
2010-01-02,USW00013769,"OCEANA NAS, VA US",36.81667,-76.03333,0.00,32.0,40.9
2010-01-03,USW00013769,"OCEANA NAS, VA US",36.81667,-76.03333,0.00,30.0,38.0
2010-01-04,USW00013769,"OCEANA NAS, VA US",36.81667,-76.03333,0.00,21.0,30.0
2010-01-05,USW00013769,"OCEANA NAS, VA US",36.81667,-76.03333,0.00,21.9,28.0